[editor]
auto-format = true
auto-info = true
auto-save = true
bufferline = "multiple"
cursorline = true
cursorcolumn = true
mouse = true
rulers = [79, 120]

[editor.lsp]
display-messages = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[editor.whitespace.render]
tab = "all"
tabpad = "all"
nbsp = "all"

[editor.whitespace.characters]
tab = "→"
tabpad = " "
nbsp = "⍽"

[editor.indent-guides]
render = false
